apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.config.GITLAB_ROOT_PASSWORD }}
  GITLAB_ROOT_PASSWORD: {{ .Values.config.GITLAB_ROOT_PASSWORD | b64enc | quote }}
  {{ else }}
  GITLAB_ROOT_PASSWORD: {{ randAlphaNum 30 | b64enc | quote }}
  {{ end }}

  DB_USER: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  DB_PASS: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.redisPassword | b64enc | quote }}

  {{ if .Values.config.GITLAB_SECRETS_DB_KEY_BASE }}
  GITLAB_SECRETS_DB_KEY_BASE: {{ .Values.config.GITLAB_SECRETS_DB_KEY_BASE | b64enc | quote }}
  {{ else }}
  GITLAB_SECRETS_DB_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.config.GITLAB_SECRETS_SECRET_KEY_BASE }}
  GITLAB_SECRETS_SECRET_KEY_BASE: {{ .Values.config.GITLAB_SECRETS_SECRET_KEY_BASE | b64enc | quote }}
  {{ else }}
  GITLAB_SECRETS_SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.config.GITLAB_SECRETS_OTP_KEY_BASE }}
  GITLAB_SECRETS_OTP_KEY_BASE: {{ .Values.config.GITLAB_SECRETS_OTP_KEY_BASE | b64enc | quote }}
  {{ else }}
  GITLAB_SECRETS_OTP_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}


